# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: af25d1644b267615a900ea768cf33890e5f3b8f8e092b1b3c73339949185b76c582e034a27c7e73513d5c3ba39e6e97f926914be242527944f192b93b5710225

test:
  secret_key_base: 1788ff6b8e15937a2f8d149490b60aa2c21de448b6e1d055798f3f29fb7d92645ba7584a1c94f856da3ef6365987b8537721a1d2944f3f4932b6a17bbf93fadc

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
